# Generated by Django 3.2.9 on 2021-11-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanturi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produse',
            name='size',
        ),
        migrations.AddField(
            model_name='produse',
            name='chain_length',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
