# Generated by Django 3.2.9 on 2021-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanturi', '0002_auto_20211122_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
