# Generated by Django 3.2.9 on 2022-01-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_authuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
