# Generated by Django 3.2.9 on 2022-02-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_authuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='password'),
        ),
    ]
