# Generated by Django 3.2.9 on 2022-02-09 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220209_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 11, 0, 58, 269388, tzinfo=utc)),
        ),
    ]
