# Generated by Django 3.2.9 on 2022-02-16 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220210_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 10, 51, 37, 50758, tzinfo=utc)),
        ),
    ]
