# Generated by Django 3.2.9 on 2021-11-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='stone_color',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
