# Generated by Django 3.2.9 on 2022-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandative', '0005_remove_produse_stone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='stone_color',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
