# Generated by Django 3.2.9 on 2022-02-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingouri', '0004_alter_produse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produse',
            name='greutate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
