# Generated by Django 3.2.9 on 2022-02-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingouri', '0005_alter_produse_greutate'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='forma_pandativ',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
