# Generated by Django 3.2.9 on 2021-11-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cercei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='sistem_inchidere',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
