# Generated by Django 3.2.9 on 2021-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bratara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color_gold', models.CharField(max_length=10)),
                ('greutate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
    ]
