# Generated by Django 3.2.9 on 2022-02-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bijuterii', '0003_auto_20220218_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bijuterie',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
