# Generated by Django 3.2.9 on 2022-02-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bijuterii', '0004_auto_20220222_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culoareaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bijuterie', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BijuterieCuloareaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bijuterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_pivot', to='bijuterii.bijuterie')),
                ('culoareaur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bijuterii_pivot', to='bijuterii.culoareaur')),
            ],
        ),
    ]
