# Generated by Django 3.2.9 on 2022-02-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bijuterii', '0006_auto_20220224_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bijuterieculoareaur',
            name='extra_column',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
