# Generated by Django 3.2.9 on 2021-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inele', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='inner_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produse',
            name='stone_color',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='produse',
            name='stone_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
